# Generated by Django 3.0.7 on 2020-06-27 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_cap', models.CharField(max_length=50)),
                ('about_title', models.CharField(max_length=100)),
                ('about_top_title', models.CharField(max_length=100)),
                ('about_top_text', models.TextField()),
                ('about_main_text', models.TextField()),
                ('about_second_text', models.TextField()),
                ('about_third_text', models.TextField()),
                ('about_bottom_title', models.CharField(max_length=100)),
                ('about_bottom_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_cap', models.CharField(max_length=100)),
                ('banner_title', models.CharField(max_length=254)),
                ('banner_img', models.ImageField(upload_to='img/banners')),
            ],
        ),
        migrations.CreateModel(
            name='ClientHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_cap', models.CharField(max_length=50)),
                ('client_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClientImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_cap', models.ImageField(upload_to='img/clients')),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_number', models.IntegerField()),
                ('counter_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FooterAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_title', models.CharField(max_length=50)),
                ('address_link', models.CharField(max_length=254)),
                ('address_hint', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FooterMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menus_title', models.CharField(max_length=50)),
                ('menus_link', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='FooterSocialIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=50)),
                ('icon_link', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='FooterSocialText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NavbarLeftIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_icon', models.CharField(max_length=50)),
                ('social_link', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NavbarLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_img', models.ImageField(upload_to='img/logos')),
            ],
        ),
        migrations.CreateModel(
            name='NavbarMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_text', models.CharField(max_length=50)),
                ('mail_link', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NavbarPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_text', models.CharField(max_length=50)),
                ('phone_link', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NewsHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_cap', models.CharField(max_length=50)),
                ('news_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/news')),
                ('news_type', models.CharField(blank=True, max_length=50, null=True)),
                ('news_title', models.CharField(max_length=100)),
                ('news_text_main', models.TextField()),
                ('news_quote', models.TextField(blank=True, null=True)),
                ('news_text_secondary', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_cap', models.CharField(max_length=50)),
                ('partner_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_cap', models.ImageField(upload_to='img/partners')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_cap', models.CharField(max_length=100)),
                ('service_title', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_icon', models.CharField(max_length=100)),
                ('item_title', models.CharField(max_length=50)),
                ('item_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TariffAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_about_first', models.TextField()),
                ('tariff_about_second', models.TextField()),
                ('tariff_about_third', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_customer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_name', models.CharField(max_length=50)),
                ('tariff_speed', models.IntegerField()),
                ('tariff_speed_night', models.IntegerField()),
                ('tariff_speed_tasix', models.IntegerField()),
                ('tariff_price', models.IntegerField()),
                ('type_customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='citynet.TypeCustomer')),
            ],
        ),
        migrations.CreateModel(
            name='AboutItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_icon', models.CharField(blank=True, max_length=50, null=True)),
                ('item_text', models.CharField(max_length=50)),
                ('about', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='citynet.About')),
            ],
        ),
    ]
