# Generated by Django 3.0.7 on 2020-06-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citynet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/logos')),
            ],
        ),
        migrations.CreateModel(
            name='TitleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/logos')),
            ],
        ),
        migrations.RenameField(
            model_name='clientimage',
            old_name='client_cap',
            new_name='client_image',
        ),
        migrations.RenameField(
            model_name='footermenu',
            old_name='menus_link',
            new_name='menu_link',
        ),
        migrations.RenameField(
            model_name='footermenu',
            old_name='menus_title',
            new_name='menu_title',
        ),
        migrations.RenameField(
            model_name='partnerimage',
            old_name='partner_cap',
            new_name='partner_image',
        ),
    ]
