# Generated by Django 3.0.7 on 2020-06-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citynet', '0003_about_about_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_cap', models.CharField(max_length=100)),
                ('tariff_title', models.CharField(max_length=254)),
            ],
        ),
    ]
