# Generated by Django 3.0.7 on 2020-06-28 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citynet', '0004_tariffheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='type_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citynet.TypeCustomer'),
        ),
    ]
