# Generated by Django 3.0.7 on 2020-06-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citynet', '0005_auto_20200628_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='tariff_button',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
