# Generated by Django 3.0.7 on 2020-06-29 07:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('citynet', '0006_tariff_tariff_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersocialtext',
            name='title',
            field=models.CharField(default=datetime.datetime(2020, 6, 29, 7, 10, 57, 909983, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
