from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(TitleImage)
admin.site.register(LoaderImage)
admin.site.register(NavbarLeftIcon)
admin.site.register(NavbarMail)
admin.site.register(NavbarPhoneNumber)
admin.site.register(NavbarLogo)
admin.site.register(Banner)
admin.site.register(ServiceHeader)
admin.site.register(ServiceItem)
admin.site.register(Counter)
admin.site.register(About)
admin.site.register(AboutItem)
admin.site.register(TariffHeader)
admin.site.register(TypeCustomer)
admin.site.register(Tariff)
admin.site.register(TariffAbout)
admin.site.register(PartnerHeader)
admin.site.register(PartnerImage)
admin.site.register(ClientHeader)
admin.site.register(ClientImage)
admin.site.register(NewsHeader)
admin.site.register(NewsItem)
admin.site.register(FooterMenu)
admin.site.register(FooterAddress)
admin.site.register(FooterSocialText)
admin.site.register(FooterSocialIcon)
admin.site.register(FooterAuthor)
admin.site.register(GetInTouch)